apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: savirman/nginx:0.0.2
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:1.0'
        args:
          - '-nginx.scrape-uri=http://localhost/basic_status'
        ports:
          - containerPort: 9113
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx
          name: nginx
