config:
  outputs: |
    [OUTPUT]
        Name  es
        Match *
        Host  elasticsearch
        Port  9200
        Suppress_Type_Name On
        Replace_Dots    On
        
        
nodeSelector:
  yandex.cloud/node-group-id:  catef5j30arm2fa1lcdj
tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule
