prometheus:
  nodeSelector:
    yandex.cloud/node-group-id: catef5j30arm2fa1lcdj
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.158.160.142.140.nip.io
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  nodeSelector:
    yandex.cloud/node-group-id: catef5j30arm2fa1lcdj
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.158.160.142.140.io
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
