apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
commonLabels:
  app: dev-redis-cart
  env: dev
namespace: hipster-shop
namePrefix: dev-
images:
  - name: redis-cart
    newName: gcr.io/google-samples/microservices-demo/adservice
    newTag: v0.6.1
